version: '3.8'
services:
  sso-db:
    image: postgres:15-alpine3.19
    env_file:
      - ./docker/sso/sso-db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d summer" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    networks:
      - sso_net
    volumes:
      - ./docker/sso/db-scripts:/docker-entrypoint-initdb.d/
      - sso-data:/var/lib/postgresql/data
    restart: unless-stopped
  sso-server:
    image: sso-server:0.0.1
    build:
      context: ./simple-sso
      dockerfile: Dockerfile
    ports:
      - "8079:8080"
    depends_on:
      - sso-db
    networks:
      - apis_net
      - sso_net
    env_file:
      - ./docker/sso/sso-server.env

  users-db:
    image: postgres:15-alpine3.19
    env_file:
      - ./docker/users/users-db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d summer" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5432"
    networks:
      - users_net
    volumes:
      - ./docker/users/db-scripts:/docker-entrypoint-initdb.d/
      - users-data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "80:80"
    networks:
      - apis_net
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d


volumes:
  sso-data:
  users-data:

networks:
  apis_net:
    driver: bridge
  sso_net:
    driver: bridge
  users_net:
    driver: bridge
